=== gspandy/csims/WebContent/WEB-INF/dtd/jGuardAuthentication_1.00.dtd
<!--
jGuard is a security framework based on top of jaas (java authentication and authorization security).
it is written for web applications, to resolve simply, access control problems.
version $Name:  $
http://sourceforge.net/projects/jguard/

Copyright (C) 2004  Charles GAY

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


jGuard project home page:
http://sourceforge.net/projects/jguard/

-->

<!-- jGuardAuthentication_1.00.dtd-->
<!ELEMENT configuration (authentication)>
<!ELEMENT authentication (scope,debug,includeOldConfig,includeConfigFromJavaParam,includePolicyFromJavaParam,salt?,digestAlgorithm?,authenticationManager,authenticationManagerOptions,loginModules)>
<!ELEMENT includeOldConfig (#PCDATA)>
<!ELEMENT includeConfigFromJavaParam (#PCDATA)>
<!ELEMENT includePolicyFromJavaParam (#PCDATA)>
<!ELEMENT scope (#PCDATA)>
<!ELEMENT debug (#PCDATA)>
<!ELEMENT loginModules (loginModule+)>
<!ELEMENT loginModule (name,flag,loginModuleOptions*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT flag (#PCDATA)>
<!ELEMENT loginModuleOptions (option+)>
<!ELEMENT option (name,value)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT salt (#PCDATA)>
<!ELEMENT digestAlgorithm (#PCDATA)>
<!ELEMENT authenticationManager (#PCDATA)>
<!ELEMENT authenticationManagerOptions (option+)>

=== gspandy/csims/WebContent/WEB-INF/conf/jguard/jGuardAuthentication_oracle.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE configuration SYSTEM "../../dtd/jGuardAuthentication_1.00.dtd">
<configuration>
	<authentication>
		<scope>local</scope>
		<debug>true</debug>
		<includeOldConfig>false</includeOldConfig>
		<includeConfigFromJavaParam>false</includeConfigFromJavaParam>
		<includePolicyFromJavaParam>false</includePolicyFromJavaParam>
		<!-- <salt>582697sweetjg</salt> -->
		<digestAlgorithm>MD5</digestAlgorithm>
		<authenticationManager>
			net.sf.jguard.ext.authentication.manager.JdbcAuthenticationManager
		</authenticationManager>
		<authenticationManagerOptions>
			<option>
				<name>JNDI</name>
				<value>java:/comp/env/jdbc/sweetOracle</value>
			</option>
			<!-- <option>
				<name>databaseDriver</name>
				<value>oracle.jdbc.driver.OracleDriver</value>
				</option>
				<option>
				<name>databaseDriverUrl</name>
				<value>jdbc:oracle:thin:@localhost:1521:XE</value>
				</option>
				<option>
				<name>databaseDriverLogin</name>
				<value>sweet</value>
				</option>
				<option>
				<name>databaseDriverPassword</name>
				<value>sweet</value>
				</option>
			 -->
			<option>
				<name>authenticationXmlFileLocation</name>
				<value>
					WEB-INF/conf/jguard/jGuardUsersPrincipals.xml
				</value>
			</option>
			<option>
				<name>authenticationDatabaseFileLocation</name>
				<value>
					WEB-INF/conf/jguard/authentication.oracle.properties
				</value>
			</option>
		</authenticationManagerOptions>

		<loginModules>
		<!-- 
			<loginModule>
				<name>
					net.sf.jguard.ext.authentication.loginmodules.JCaptchaLoginModule
				</name>
				<flag>REQUIRED</flag>
			</loginModule>
		 -->
			<loginModule>
				<name>
					net.sf.jguard.ext.authentication.loginmodules.JdbcLoginModule
				</name><!-- net.sweet.security.Axis1LoginModule -->
				<flag>REQUIRED</flag>
				<loginModuleOptions>
					<option>
						<name>debug</name>
						<value>false</value>
					</option>
				</loginModuleOptions>
			</loginModule>
		</loginModules>
	</authentication>
</configuration>
