=== gspandy/csims/WebContent/WEB-INF/dtd/jGuardFilter_1.00.dtd
<!--
jGuard is a security framework based on top of jaas (java authentication and authorization security).
it is written for web applications, to resolve simply, access control problems.
version $Name:  $
http://sourceforge.net/projects/jguard/

Copyright (C) 2004  Charles GAY

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


jGuard project home page:
http://sourceforge.net/projects/jguard/

-->

<!-- jGuardFilter_1.00.dtd-->
<!ELEMENT configuration (filter)>
<!ELEMENT filter (indexURI,authenticationFailedURI,logonURI,logonProcessURI,registerURI,registerProcessURI,logoffURIs,accessDeniedURI,authScheme,loginField?,passwordField?,goToLastAccessDeniedUriOnSuccess)>
<!ELEMENT logoffURIs (logoffURI+)>
<!ELEMENT loginField (#PCDATA)>
<!ELEMENT passwordField (#PCDATA)>
<!ELEMENT indexURI (#PCDATA)>
<!ELEMENT authenticationFailedURI (#PCDATA)>
<!ELEMENT logonURI (#PCDATA)>
<!ELEMENT logonProcessURI (#PCDATA)>
<!ELEMENT registerURI (#PCDATA)>
<!ELEMENT registerProcessURI (#PCDATA)>
<!ELEMENT logoffURI (#PCDATA)>
<!ELEMENT accessDeniedURI (#PCDATA)>
<!ELEMENT authScheme (#PCDATA)>
<!ELEMENT goToLastAccessDeniedUriOnSuccess (#PCDATA)>

=== gspandy/csims/WebContent/WEB-INF/conf/jguard/jGuardFilter.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE configuration SYSTEM "../../dtd/jGuardFilter_1.00.dtd">
<configuration>
	<filter>
		<indexURI>/index.jsp</indexURI>
		<authenticationFailedURI>
			/AuthenticationFailed.do
		</authenticationFailedURI>
		<logonURI>/Logon.do</logonURI>
		<logonProcessURI>/LogonProcess.do</logonProcessURI>
		<registerURI>/Registration.do</registerURI>
		<registerProcessURI>/RegistrationProcess.do</registerProcessURI>
		<logoffURIs>
			<logoffURI>/Logoff.do</logoffURI>
		</logoffURIs>
		<accessDeniedURI>/AccessDenied.do</accessDeniedURI>
		<authScheme>FORM</authScheme>
		<loginField>login</loginField>
		<passwordField>password</passwordField>
		<goToLastAccessDeniedUriOnSuccess>
			false
		</goToLastAccessDeniedUriOnSuccess>
	</filter>
</configuration>
